services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://db:27017/vidly
      PORT: 3001
    depends_on:
      - db
    command: sh ./docker-entrypoint.sh

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - vidly_data:/data/db

volumes:
  vidly_data: